### ISSUE TITLE
catalog of open and globular clusters

### ISSUE THREAD

**Issue by davidwhogg** [davidwhogg/Platypus#4]
I need the best possible lists I can get of open and globular clusters, with (ideally)
- cluster name
- RA, Dec (or l, b)
- heliocentric radial velocity

@andycasey @mkness where do I find these, and/or can you check them in to this repo somewhere?

and/or do I just query something on the web?

**Comment by andycasey** [comment]
Harris is the best catalog of globular clusters: http://www.physics.mcmaster.ca/~harris/mwgc.dat

I don't know of anything similar for open clusters, but I know who will know.

**Comment by andycasey** [comment]
Two open cluster catalogs:

http://www.wilton.unifei.edu.br/ocdb/

https://www.univie.ac.at/webda/

All of these are in shitty, shitty formats. Leave this issue open until we (I??) have put them altogether into a usable form.
