### ISSUE TITLE
Palomar 5 is actually M5

### ISSUE THREAD

**Issue by andycasey** [davidwhogg/Platypus#41]
They are both in the same field and were collectively targeted by APOGEE as `M5PAL5`, but the clustering in abundance space is actually the globular cluster M5 (NGC 5904).

**Comment by davidwhogg** [comment]
Woah good catch

**Comment by andycasey** [comment]
I take no credit for this; @anguswilliams91 [caught it](https://github.com/anguswilliams91/Pal5).

**Comment by davidwhogg** [comment]
Then we must also remember to ack him

**Comment by davidwhogg** [comment]
Fixed this, but there is still a paragraph about Palomar 5 abundances that has to be replaced with one about M5 abundances!! Argh!

**Comment by davidwhogg** [comment]
@andycasey can you look at the Pal5 paragraph in the discussion, and write a similar (or shorter) one about M5 with a few references? I will gladly pay beer for this.

**Comment by andycasey** [comment]
Can be closed once #46 is merged.
