### ISSUE TITLE
OMG aastex 6 is unreadable

### ISSUE THREAD

**Issue by davidwhogg** [davidwhogg/Platypus#43]
How do we get 1.13 spacing and 12-pt text in single-column preprint form? ARGH.

**Comment by davidwhogg** [comment]
and OMG references are LIGHT BLUE!

**Comment by andycasey** [comment]
Actually fixed on master in bd7b5f1 and e0df2a9: 60b522e was accidentally committed on a stale branch.

It shows as 12pt manuscript format now and references are black.

However I still think AASTeX v6 is largely unreadable, so I'm leaving this open until Hogg deems it closed. Maybe I'm just not used to v6 yet.

**Comment by davidwhogg** [comment]
OMG so many things. I will switch it to 11/13 spacing, adjust parindents, and maybe margin tweaks, and contact AASTEX...!

Thanks for helping / understanding this one.

**Comment by andycasey** [comment]
I've already contacted Greg Schwartz and August Meunch (sp?) twice about (1) the center-left-center justification of the title-affiliations-abstract,(2) how to provide context in the \software tag (e.g., "this research benefitted from..")

I've found they're helpful and receptive to comments, and seem to agree that the new style might be sub-optimal in some ways.

**Comment by davidwhogg** [comment]
I am going to revert your changes to AASTEX -- we can't edit that, because arXiv will over-rule with its own install; we have to punk it in our own latex header. Reverting some changes...

**Comment by davidwhogg** [comment]
Dude, the AASTEX 6 has bugs as well as bad choices. Do they have an issue / ticket system?

**Comment by dfm** [comment]
https://github.com/AASJournals/AASTeX60

**Comment by davidwhogg** [comment]
@dfm thanks for this; I just opened 5 (or so) issues there. I am closing this for now, since I have something that doesn't make my eyes bleed (only water).
